config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resource :session, only: [:new, :create, :destroy]
    resources :users
  end

  resources :movies do
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  root to: 'movies#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews

  mount_uploader :image, ImageUploader

  validates :title, :director, :description, :release_date, presence: true
  validates :runtime_in_minutes, numericality: {only_integer: true}
  validate :release_date_is_in_the_future

  scope :search_by_title, -> (string) {where("title like ? or director like ?", "%#{string}%", "%#{string}%")}
  # scope :search_by_director, -> (string) {where("director like ?", "%#{string}%")}
  scope :search_shorter_than_90, -> {where("runtime_in_minutes < 90")}
  scope :search_between_90_120, -> {where(runtime_in_minutes: 90..120)}
  scope :search_longer_than_120, -> {where("runtime_in_minutes > 120")}

  def review_average
    reviews.sum(:rating_out_of_ten)/reviews.size
  end

  protected

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :movie

  validates :user, :movie, :text, presence: true

  validates :rating_out_of_ten, numericality: {only_integer: true}
  validates :rating_out_of_ten, numericality: {greater_than_or_equal_to: 1}
  validates :rating_out_of_ten, numericality: {less_than_or_equal_to: 10}
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :reviews

  after_destroy :delete_email_notification

  def delete_email_notification
    @user = self
    UserMailer.delete_email(@user)
  end

  def full_name
    "#{firstname} #{lastname}"
  end
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
 
  # before_filter :authorize

  def index
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password]) && user.admin
      session[:user_id] = user.id
      redirect_to admin_url
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_admin_session_path, notice: "Adios!"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_access

  def index
    @users = User.all.page(params[:page]).per(2)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:admin_user_id] = @user.id
        format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: [:admin,@user] }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    else
      if current_user.admin != true
        flash[:alert] = "You are not logged in as an admin."
        redirect_to admin_path 
      end
    end
  end

  # def admin_access
  #   # if !admin_user
  #     if admin_user.try(:admin)
  #       flash[:alert] = "You are not logged in as an admin."
  #       redirect_to new_admin_session_path
  #     end
  #   # end
  # end

  # def admin_user
  #   @admin_user ||= User.find(session[:admin_user_id]) if session[:admin_user_id]
  # end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  # helper_method :admin_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all

    @movies = Movie.search_by_title(params[:q]) unless params[:q].blank?
    
    # @movies = Movie.search_by_director(params[:r]) unless params[:r].blank?

    if params[:duration].to_i == 1
      @movies = Movie.search_shorter_than_90
    end
    if params[:duration].to_i == 2
      @movies = Movie.search_between_90_120
    end
    if params[:duration].to_i == 3
      @movies = Movie.search_longer_than_120
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end
  
  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image, :remote_image_url
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id 

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_i] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1>

<% if current_user && current_user.admin == true %>
  <ul>
    <li><%= link_to 'Manage Users', admin_users_path %></li>
  </ul>
<% else %>
  <p>Please <%= link_to "log in", new_admin_session_path %> to see access the administrative tools.</p> 
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User Info</h1>
<% if current_user && current_user.admin == true %>
  <%= form_for(@user, url: admin_user_path) do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :firstname, "First Name" %><br>
      <%= f.text_field :firstname %>
    </div>
    <div>
      <%= f.label :lastname, "Last Name" %><br>
      <%= f.text_field :lastname %>
    </div>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div><%= f.submit "Submit" %></div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_admin_session_path %> as an admin to access the administrative tools.</p> 
<% end %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<% if current_user && current_user.admin == true %>

<%= paginate @users %>

  <table>
    <tr>
      <th>Email</th>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.email, admin_user_path(user) %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New User', new_admin_user_path %>

<% else %>
  <p>Please <%= link_to "log in", new_admin_session_path %> as an admin to access the administrative tools.</p> 
<% end %>

app/views/admin/users/new.html.erb
<h1>New user</h1>
<% if current_user && current_user.admin == true %>
  <%= form_for([:admin,@user]) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :firstname, "First Name" %><br>
      <%= f.text_field :firstname %>
    </div>
    <div>
      <%= f.label :lastname, "Last Name" %><br>
      <%= f.text_field :lastname %>
    </div>
    <div>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div><%= f.submit "Submit" %></div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_admin_session_path %> as an admin to access the administrative tools.</p> 
<% end %>

app/views/admin/users/show.html.erb
<%= link_to "Back to all users", admin_users_path %><br/>

<% if current_user && current_user.admin == true %>

  <h2><%= @user.firstname %> (<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %>)</h2>
<% else %>
  <p>Please <%= link_to "log in", new_admin_session_path %> as an admin to access the administrative tools.</p> 
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user && current_user.admin == true %>
      Signed in as an admin, <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>) <%= link_to "Admin Panel", admin_path %>
    <% else %>
      <% if current_user %>
        Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% else %>
        <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
      <% end %>
    <% end %>

  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>

<%= yield %>
<% console %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:multipart => true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div>
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.file_field :image %>
  </div>
  <div>
    <%= f.label :remote_image_url, "or image URL" %><br/>
    <%= f.text_field :remote_image_url %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
 <% movies.each do |movie| %>

 <%= link_to image_tag(movie.image_url(:thumb).to_s), movie_path(movie) %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
  <hr>

  <% end %>

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>

<h2>Edit this movie.</h2>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Rotten Mangoes</h1>
<%= link_to "Submit a movie!", new_movie_path %>
<hr>

<%= form_tag("/movies", method: "get") do %>
  <%= label_tag(:q, "Search by Title or Director:") %>
  <%= text_field_tag(:q) %>
  <%= label_tag(:duration, "Search by Duration:") %>
  <%= select_tag(:duration, options_for_select([["Select a duration", 0], ["Under 90 minutes", 1], ["Between 90 and 120 minutes", 2], ["Over 120 minutes", 3]], 0)) %>
  <%= submit_tag("Search") %>
<% end %>


<%= render partial: "movie", locals: {movies: @movies} %>
 

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>
<h2>Submit a movie!</h2>

<%= render 'form' %>

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>

<%= image_tag(@movie.image_url(:thumb2).to_s) %>
<h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
<% if current_user %>
  <% @movie.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
    <small>- <%= review.user.full_name %></small><br/>
  <% end %>
  <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
    <%= link_to "Back to movie", movie_path(@movie) %><br/>

    <h2>Write a review of <em><%= @movie.title %></em>.</h2>

    <%= form_for([@movie, @review]) do |f| %>
      <% if @review.errors.any? %>
        <div>
          <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
          <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= f.label :text %><br>
        <%= f.text_area "text" %>
      </div>
      <div>
        <%= f.label :rating_out_of_ten %><br>
        <%= f.number_field :rating_out_of_ten %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :firstname, "First Name" %><br>
        <%= f.text_field :firstname %>
      </div>
      <div>
        <%= f.label :lastname, "Last Name" %><br>
        <%= f.text_field :lastname %>
      </div>
      <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>